server:
    port: 8061
    context-path: /
spring:
    datasource:
        url: jdbc:mysql://192.168.18.228:3306/installment?&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
        username: xinge
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

logging:
    level:
        root: info
        com.xinge.installment: debug

sms:
    validate:
        super:
            #超级验证开关
            open: true
            #超级验证码
            code: 888888
        #验证码长度
        length: 6
