server:
    port: 8061
    context-path: /
spring:
    datasource:
        url: jdbc:mysql://localhost:3306/test?&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
        username: root
        password: 123456
        driver-class-name: com.mysql.jdbc.Driver

logging:
    level:
        root: info
        com.xinge.demo: debug
