server:
    port: 80
    context-path: /
    tomcat:
      basedir: tmp
spring:
    datasource:
        url:
        username:
        password:
        driver-class-name: com.mysql.jdbc.Driver

logging:
    level:
        root: info
        com.xinge.demo: debug

