server:
    port: 80
    context-path: /
    tomcat:
      basedir: tmp
spring:
    datasource:
        url: jdbc:p6spy:mysql://localhost:3306/testdb?&useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&tinyInt1isBit=false
        username: root
        password: 123456
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        druid:
          db-type: mysql

logging:
    level:
        root: info

