server:
    port: 8061
    context-path: /
    tomcat:
      basedir: tmp
spring:
    datasource:
        url:
        username:
        password:
        driver-class-name: com.mysql.jdbc.Driver

logging:
    level:
      root: info

sms:
    validate:
        super:
            #超级验证开关，默认false
            open: false
            #超级验证码，默认888888
            code: 888888
        #验证码长度，默认6
        length: 6
