server:
    port: 8061
    context-path: /
    tomcat:
      basedir: tmp
spring:
    datasource:
        url:
        username:
        password:
        driver-class-name: com.mysql.jdbc.Driver

logging:
    level:
      root: info
