server:
    port: 80
    context-path: /
spring:
    datasource:
        url: jdbc:p6spy:h2:file:~/.h2/testdb
        username: root
        password: 123456
        driver-class-name: com.p6spy.engine.spy.P6SpyDriver
        schema: classpath:db/schema.sql
        data: classpath:db/data.sql
        druid:
          db-type: h2

logging:
    level:
        root: info
