server:
    port: 80
    context-path: /
spring:
    datasource:
        url: jdbc:h2:file:~/.h2/testdb
        username: root
        password: 123456
        driver-class-name: org.h2.Driver
        schema: classpath:db/schema.sql
        data: classpath:db/data.sql

logging:
    level:
        root: info
        com.xinge.demo: debug
